version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: taxi_db
      POSTGRES_USER: taxi_user
      POSTGRES_PASSWORD: taxi_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U taxi_user -d taxi_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  etl_app:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: taxi_db
      DB_USER: taxi_user
      DB_PASSWORD: taxi_password
    volumes:
      - ./data:/app/data

volumes:
  postgres_data: